### ISSUE TITLE
Confirm that the vscode-extension is compatible with RHINO-CLI and RHINO-Operator v1alpha2

### ISSUE THREAD

**Issue by LI-Mingyu** [OpenRHINO/vscode-extension#1]
The RHINO-Operator and RHINO-CLI were upgraded to v1alpha2 in https://github.com/OpenRHINO/RHINO-Operator/pull/48 and https://github.com/OpenRHINO/RHINO-CLI/pull/88 respectively. 

We need to confirm that the vscode-extension is compatible with RHINO-CLI and RHINO-Operator v1alpha2. If it is not, we need to fix it.

**Comment by TimeSea05** [comment]
![image](https://github.com/OpenRHINO/vscode-extension/assets/75821338/94b73d1f-1f93-4877-b98e-5fdc58690f91)
已经完成的项目
* 在侧边栏添加`Creation Time`一项
* 在 rhino run 命令中让用户选择`mem-mode`与`mem-size`
不知是否有遗漏

**Comment by LI-Mingyu** [comment]
Solved
